# Generated by Django 3.0.11 on 2020-11-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('IN', 'Individual'), ('OR', 'Organization')], default='IN', max_length=2),
        ),
    ]
